# =========================
# AdvancedBungeeAnnouncer configuration
# =========================

#
# ++ ANNOUNCEMENTS.YML HAS THE ANNOUNCEMENTS. ++
#         They are _NOT_ in this file!
#

# --
# ANNOUNCER CUSTOMIZATION
# --

# AdvancedBungeeAnnouncer runs on a static delay between all announcements.
# This value lets you change the delay. It must be specified in seconds.
# Default: 180 (3 minutes)

delay: 180

# This option changes how announcements are selected.
# Choices available:
# - sequential: default, picks announces as they are iterated over
# - random: picks a random announcement for each server

choose-announcement-via: sequential

# This lets you set a prefix for the announcements.
# Useful if you want to give your network an "identity" of sorts.

prefix: ""

# Choose how the announcements are displayed.
# Choices available:
# - chat: Sends messages to chat
# - action: Sends the announcement as an above action bar message (>=1.8)
# - title: Sends the announcement as a title. (>=1.8)
# - boss_bar: Sends the announcement as a boss bar message. (>=1.9)

display: chat

# Allows to customize how long the action bar remains on the screen.
# The message will be present for this many seconds at least.
# Values below or equal to 1 will only send the message once.
action-bar-period: 1

# Allows to customize the display of titles to clients.
title:
  title: "&c&lAnnouncement"
  fade-in: 40
  stay: 80
  fade-out: 40

# Boss bar configuration.
bar-display:
  # Colors: PINK, BLUE, RED, GREEN, YELLOW, PURPLE, WHITE
  color: white
  # Divisions: NONE, SIX, TEN, TWELVE, TWENTY
  # You can _not_ use numbers, you must use these words.
  division: solid